server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test_microservice
    username: root
    password: Admin@123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: PRODUCT-SERVICE
  config:
    import: configserver:http://localhost:8085

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-54286080.okta.com/oauth2/default
      client:
        registration:
          my-internal-client-product:
            provider: okta
            authorizationGrantType: client_credentials
            scope: internal
            client-id: 0oadgpwrxojimpSmh5d7
            client-secret: mtdh6g_GdKW7OqtH37bjAjmRhv3NxDqu999EGuLtZlurYSDTavyE-WitbY3Iqsbf
        provider:
          okta:
            issuerUri: https://dev-54286080.okta.com/oauth2/default

okta:
  oauth2:
    issuer: https://dev-54286080.okta.com/oauth2/default
    audience: api://default