server:
  port: 8083

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test_microservice
    username: root
    password: Admin@123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: RATING-SERVICE
  config:
    import: configserver:http://localhost:8085

okta:
  oauth2:
    issuer: https://dev-54286080.okta.com/oauth2/default
    audience: api://default
